
spring:
    data:
        mongodb:
          uri: mongodb://root:123456@localhost:27017/dbName
server:
  port: 8081


#spring.data.mongodb.uri=mongodb://name:pass@localhost:27017/test
#spring.data.mongodb.uri=mongodb://192.168.1.1:20000,192.168.1.2:20000,192.168.252.12:20000/test